$desk = "C:\Users\vledoux\Documents\OneDrive - SED\Bureau"
$jahbless = "C:\Users\vledoux\"
$docs = "C:\Users\vledoux\Documents"
$soft = "C:\Users\vledoux\OneDrive - SED\home\Soft"
$powershell_folder = "C:\Users\vledoux\OneDrive - SED\home\powershell"
$tradsh_path = "C:\Users\vledoux\OneDrive - SED\home\powershell\config\tradsh.ps1"